export const webinarData = [
  {
    title: "Make your first $1000",
    description: "Hosted by Emmanuel Prein",
    duration: "20m 30s",
    webinarDate: new Date("2023-10-01"),
    thumbnail:"",
    link:"/webinar",
  },
  {
    title: "Make your first $1000",
    description: "Hosted by Emmanuel Prein",
    duration: "20m 30s",
    webinarDate: new Date("2023-10-01"),
    thumbnail:"",
    link:"/webinar",
  },
  {
    title: "Make your first $1000",
    description: "Hosted by Emmanuel Prein",
    duration: "20m 30s",
    webinarDate: new Date("2023-10-01"),
    thumbnail:"",
    link:"/webinar",
  },
  {
    title: "Make your first $1000",
    description: "Hosted by Emmanuel Prein",
    duration: "20m 30s",
    webinarDate: new Date("2023-10-01"),
    thumbnail:"",
    link:"/webinar",
  },
  {
    title: "Make your first $1000",
    description: "Hosted by Emmanuel Prein",
    duration: "20m 30s",
    webinarDate: new Date("2023-10-01"),
    thumbnail:"",
    link:"/webinar",
  },
  {
    title: "Make your first $1000",
    description: "Hosted by Emmanuel Prein",
    duration: "20m 30s",
    webinarDate: new Date("2023-10-01"),
    thumbnail:"",
    link:"/webinar",
  },
  {
    title: "Make your first $1000",
    description: "Hosted by Emmanuel Prein",
    duration: "20m 30s",
    webinarDate: new Date("2023-10-01"),
    thumbnail:"",
    link:"/webinar",
  },
  {
    title: "Make your first $1000",
    description: "Hosted by Emmanuel Prein",
    duration: "20m 30s",
    webinarDate: new Date("2023-10-01"),
    thumbnail:"",
    link:"/webinar",
  },
  {
    title: "Make your first $1000",
    description: "Hosted by Emmanuel Prein",
    duration: "20m 30s",
    webinarDate: new Date("2023-10-01"),
    thumbnail:"",
    link:"/webinar",
  },
  {
    title: "Make your first $1000",
    description: "Hosted by Emmanuel Prein",
    duration: "20m 30s",
    webinarDate: new Date("2023-10-01"),
    thumbnail:"",
    link:"/webinar",
  },

 
]